version: "2"

run:
  tests: false

linters:
  default: none
  enable:
    - goconst
    - misspell
    - unused
    - staticcheck
    - unconvert
    - ineffassign
    - revive
  settings:
    goconst:
      min-len: 5
      min-occurrences: 4
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
